### ISSUE TITLE
글 작성 페이지 구상

### ISSUE THREAD

**Issue by ieunseo** [4team-react123/react#3]
💡 구현할 기능
- 글 작성 페이지 전체적인 형태 작성 (아직 글이 작성되고, 해당 카테고리에 동적으로 올라가는 기능은 다른 페이지가 작성된 후 구현할것임)
- 관리자만 글을 작성하게 할것이고, 비밀번호는 1234 로 설정할것임.

**Comment by syongsyong6035** [comment]
네 확인 했습니다 수고하셨습니다
