### ISSUE TITLE
recycle 초기 기능 구현

### ISSUE THREAD

**Issue by Baeminseo** [4team-react123/react#8]
### ✨ 작업한 내용
- recycle 페이지에서 쓰레기 종류별로 페이지 이동해서 그 종류에 해당하는 분리수거하는 방법이 나오도록 구현 + 검색기능 추가

### 🌀 PR Point
- App.js 를 수정해서 충돌나지 않도록 해야한다.

### 🍰 참고사항
- css 구현하는 중이라 참고하고 병합해야한다.

**Comment by syongsyong6035** [comment]
확인했습니다 예뿌네용
